export function ReportFooter() {
  return (
    <footer
      className="w-full py-12 px-6 border-t"
      style={{
        borderColor: "var(--border)",
        backgroundColor: "var(--surface-sunken)",
      }}
    >
      <div className="mx-auto max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
            <p className="font-mono text-xs tracking-widest uppercase" style={{ color: "var(--accent)" }}>
              Bharat Future City
            </p>
            <p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}>
              Comprehensive Interactive Report
            </p>
          </div>
          <div className="flex flex-col items-start md:items-end gap-1">
            <p className="font-mono text-xs" style={{ color: "var(--text-dim)" }}>
              Data current as of FY 2024-25
            </p>
            <p className="font-mono text-xs" style={{ color: "var(--text-dim)" }}>
              Generated by Superagent.
            </p>
          </div>
        </div>
        <div className="mt-8 pt-6 border-t" style={{ borderColor: "var(--border)" }}>
          <p className="font-mono text-xs leading-relaxed" style={{ color: "var(--text-dim)" }}>
            This report synthesizes publicly available information, government policy documents, 
            and verified research findings. Economic projections are based on stated government targets 
            and should be interpreted as aspirational unless explicitly noted as verified.
          </p>
        </div>
      </div>
    </footer>
  )
}
